services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '80:80'
    volumes:
      - ./:/var/www/html
    environment:
      - PHP_ENV=production
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
