services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.0-apache
    container_name: treevitae_web
    ports:
      - '80:80'
    volumes:
      - ./:/var/www/html
      - ./apache.conf:/etc/apache2/sites-available/000-default.conf
    environment:
      - PHP_ENV=production
      - APACHE_DOCUMENT_ROOT=/var/www/html
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
