services:
  apache-php:
    image: apache-mysqli
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - '80:80'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
