services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.0-apache
    container_name: treevitae_web
    ports:
      - '80:80'
    volumes:
      - ./:/var/www/html:rw
    environment:
      - PHP_ENV=production
      - APACHE_DOCUMENT_ROOT=/var/www/html
    restart: always
