version: '3.8'

services:
  apache-php:
    image: apache-mysqli
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    ports:
      - '80:80'
    networks:
      - app-network

  mysql:
    image: mysql
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: pw
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: mysql
    ports:
      - '8080:80'
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
